package boundary;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import controller.AnnullaPrenotazioneController;
import dto.PrenotazioneDTO;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDate;

public class AnnullamentoPopup {

    private final AnnullaPrenotazioneController controller = new AnnullaPrenotazioneController();

    private JPanel annullamentoPanel;
    private JLabel messaggioConferma;
    private JPanel PannelloPulsanti;
    private JButton ConfermaAnnullamento;
    private JButton Indietro;

    private PrenotazioneDTO prenotazioneSelezionata;
    private DefaultTableModel modelTabella;
    private int indiceRiga;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    public AnnullamentoPopup(PrenotazioneDTO prenotazioneSelezionata, DefaultTableModel modelTabella,  int indiceRiga) {
        this.prenotazioneSelezionata = prenotazioneSelezionata;
        this.modelTabella = modelTabella;
        this.indiceRiga = indiceRiga;
        ConfermaAnnullamento.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                //eseguo il controllo sulla data
                LocalDate dataOggi = LocalDate.now();
                LocalDate limiteAnnullamento = prenotazioneSelezionata.getDataPrenotazione().minusDays(1);

                if(dataOggi.isEqual(limiteAnnullamento) || dataOggi.isAfter(limiteAnnullamento)) {
                    JOptionPane.showMessageDialog(
                            null,
                            "Non è possibile annullare la prenotazione il giorno precedente all'appuntamento.",
                            "Annullamento Non Consentito",
                            JOptionPane.ERROR_MESSAGE
                    );

                    //chiude la finestra
                    Window finestra = javax.swing.SwingUtilities.getWindowAncestor((Component) e.getSource());
                    if (finestra != null) {
                        finestra.dispose();
                    }
                }
                    else{

                    boolean successo = controller.confermaAnnullamentoPrenotazione(prenotazioneSelezionata);
                    JOptionPane.showMessageDialog(null, "Prenotazione annullata con successo.");
                    modelTabella.removeRow(indiceRiga);

                    //chiude la finestra
                    Window finestra = javax.swing.SwingUtilities.getWindowAncestor((Component) e.getSource());
                    if (finestra != null) {
                        finestra.dispose();
                    }
                    }

                }
            });
        Indietro.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                //chiude la finestra
                Window finestra = javax.swing.SwingUtilities.getWindowAncestor((Component) e.getSource());
                if (finestra != null) {
                    finestra.dispose();
                }
            }
        });
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        annullamentoPanel = new JPanel();
        annullamentoPanel.setLayout(new GridLayoutManager(2, 1, new Insets(10, 20, 20, 20), -1, -1));
        annullamentoPanel.setPreferredSize(new Dimension(430, 100));
        messaggioConferma = new JLabel();
        messaggioConferma.setText("Sei sicuro di voler annullare la prenotazione?");
        annullamentoPanel.add(messaggioConferma, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(393, 17), null, 0, false));
        PannelloPulsanti = new JPanel();
        PannelloPulsanti.setLayout(new GridLayoutManager(1, 3, new Insets(0, 0, 0, 0), -1, -1));
        annullamentoPanel.add(PannelloPulsanti, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        PannelloPulsanti.add(spacer1, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        ConfermaAnnullamento = new JButton();
        ConfermaAnnullamento.setHorizontalAlignment(0);
        ConfermaAnnullamento.setText("Si");
        PannelloPulsanti.add(ConfermaAnnullamento, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_SOUTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        Indietro = new JButton();
        Indietro.setText("No");
        PannelloPulsanti.add(Indietro, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_SOUTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return annullamentoPanel;
    }
    //classe di supporto
    public JPanel getPannelloPrincipale() {
        return (JPanel) this.$$$getRootComponent$$$();
    }

}
