package boundary;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import dto.PrenotazioneDTO;
import entity.Ombrellone;
import entity.Fila;

import javax.swing.*;
import java.awt.*;
import javax.swing.table.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDate;

public class ConsultaPropriePrenotazioni {
    private JPanel panel;
    private JTable table1;
    private JScrollPane ScrollPane1;
    private String stato;
    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel = new JPanel();
        panel.setLayout(new GridLayoutManager(1, 1, new Insets(10, 20, 10, 20), -1, -1));
        panel.setPreferredSize(new Dimension(500, 550));
        ScrollPane1 = new JScrollPane();
        panel.add(ScrollPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        ScrollPane1.setViewportView(table1);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }

    private void createUIComponents() {
        var colonne = new String[]{"Prenotazione", "Data", "Fila", "Posto", "Servizi Aggiuntivi", "Costo", " "};

        var dati = new Object[][]{};
        DefaultTableModel model = new DefaultTableModel(dati, colonne){
            @Override
            public boolean isCellEditable(int row, int column) {
                if (column == 6){
                    return true;
                }
                else return false;
            }
        };

        table1 = new JTable(model);

        TableColumn colonna = table1.getColumnModel().getColumn(6);
        // creo una classe che gestisce l'ultima colonna "bottone"
        GestoreBottoneAnnulla gestoreBottone = new GestoreBottoneAnnulla(table1, model);
        colonna.setCellRenderer(gestoreBottone);
        colonna.setCellEditor(gestoreBottone);
    }

    private class GestoreBottoneAnnulla extends AbstractCellEditor implements TableCellRenderer, TableCellEditor {

        private final JTable tabella;
        private final DefaultTableModel modello;
        private final JButton bottoneRender;
        private final JButton bottoneEditor;
        private Object valoreCella;
        private int rigaCorrente;

        public GestoreBottoneAnnulla(JTable tab, DefaultTableModel modello) {
            this.tabella = tab;
            this.modello = modello;
            this.bottoneRender = new JButton();
            this.bottoneEditor = new JButton();

            this.bottoneEditor.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    fireEditingStopped();
                    bottoneAnnullaActionPerformed(rigaCorrente);
                }
            });
        }

        @Override
        public Component getTableCellRendererComponent(JTable tab, Object val, boolean isSelected, boolean hasFocus, int riga, int col) {
            if (val == null) {
                bottoneRender.setText(""); // Se la cella è vuota non scrive niente sul bottone
            } else {
                bottoneRender.setText(val.toString()); // se c'è scritto annulla lascia annulla
            }
            return bottoneRender;
        }

        @Override
        public Component getTableCellEditorComponent(JTable tab, Object val, boolean isSelected, int riga, int col) {
            this.valoreCella = val;
            this.rigaCorrente = riga;
            if (val == null) {
                bottoneEditor.setText(""); //se la cella è vuota non scrive niente
                bottoneEditor.setEnabled(false); // fa in modo che la cella non sia cliccabile
            } else {
                bottoneEditor.setText(val.toString()); // se c'è scritto annulla lascia annulla
                bottoneEditor.setEnabled(true);

            }
            return bottoneEditor;
        }

        @Override
        public Object getCellEditorValue() {
            return this.valoreCella;
        }
    }

    private void bottoneAnnullaActionPerformed(int rigaSelezionata) {

        DefaultTableModel model = (DefaultTableModel) table1.getModel();

        //passaggio dei dati e formatting della tabella
        long idPrenotazione = (long) model.getValueAt(rigaSelezionata, 0);
        LocalDate data = (LocalDate) model.getValueAt(rigaSelezionata, 1);
        Fila fila =  (Fila) model.getValueAt(rigaSelezionata, 2);
        int posto = (int)  model.getValueAt(rigaSelezionata, 3);
        String servizi = (String) model.getValueAt(rigaSelezionata, 4);
        int costo =  (int) model.getValueAt(rigaSelezionata, 5);
//modificato nome e cognome perchè altrimenti non funziona
// da correggere
        dto.PrenotazioneDTO dtoSelezionato = new dto.PrenotazioneDTO(idPrenotazione, data, "", "",  fila, posto, servizi, costo,stato);

        AnnullamentoPopup pannelloPopup = new AnnullamentoPopup(dtoSelezionato, model, rigaSelezionata);

        //Trova la finestra principale
        Window finestraMadre = SwingUtilities.getWindowAncestor(table1);

        // Crea un JDialog
        JDialog dialog = new JDialog(finestraMadre, "Conferma Annullamento", Dialog.ModalityType.APPLICATION_MODAL);

        // Inserisce annullamentoPopup nel JDialog
        dialog.add(pannelloPopup.getPannelloPrincipale());
        //Configurazione grafica del Popup

        dialog.pack(); // Serve per dire a java di prendersi lo spazio necessario
        dialog.setLocationRelativeTo(finestraMadre); //Centra il Popup sulla finestra madre
        // Mostra la finestra
        dialog.setVisible(true);
    }
}



