package boundary;

import controller.GestionePrenotazioneController;
import dto.FilaDTO;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import javax.swing.table.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDate;
import java.util.List;

public class ConsultaPropriePrenotazioni {
    private JPanel panel;
    private JTable table1;
    private JScrollPane ScrollPane1;

    public ConsultaPropriePrenotazioni(long idCliente) {
        caricaPrenotazioniUtente(idCliente);
    }

    public void caricaPrenotazioniUtente(long idCliente) {
        List<dto.PrenotazioneDTO> lista = GestionePrenotazioneController.ottieniPrenotazioniUtente(idCliente);

        if (lista.isEmpty()) {
            // Svuota la tabella (se c'era qualcosa da sessioni precedenti)
            if (table1 != null) {
                ((DefaultTableModel) table1.getModel()).setRowCount(0);
            }

            // Mostra il popup di avviso a schermo
            JOptionPane.showMessageDialog(
                    panel,
                    "Non hai effettuato nessuna prenotazione.",
                    "Nessuna Prenotazione",
                    JOptionPane.INFORMATION_MESSAGE
            );
        } else {
            assert table1 != null;
            DefaultTableModel model = (DefaultTableModel) table1.getModel();
            model.setRowCount(0);

            for (dto.PrenotazioneDTO p : lista) {
                model.addRow(new Object[]{
                        p.getIdPrenotazione(),
                        p.getDataPrenotazione(),
                        p.getFila().getPosizione(),
                        p.getPosto(),
                        p.getServiziAggiuntivi(),
                        p.getCosto(),
                        p.getStato(),
                        "Annulla"
                });
            }
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel = new JPanel();
        panel.setLayout(new GridLayoutManager(1, 1, new Insets(10, 20, 10, 20), -1, -1));
        panel.setPreferredSize(new Dimension(500, 550));
        ScrollPane1 = new JScrollPane();
        panel.add(ScrollPane1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        ScrollPane1.setViewportView(table1);
    }

    /**
     * @noinspection ALL
     */


    public JComponent $$$getRootComponent$$$() {
        return panel;
    }

    private void createUIComponents() {
        var colonne = new String[]{"Prenotazione", "Data", "Fila", "Posto", "Servizi Aggiuntivi", "Costo","Stato", " "};
        var dati = new Object[][]{};
        DefaultTableModel model = new DefaultTableModel(dati, colonne){
            @Override
            public boolean isCellEditable(int row, int column) {
                if (column == 7){
                    return true;
                }
                else return false;
            }
        };

        table1 = new JTable(model);

        TableColumn colonna = table1.getColumnModel().getColumn(7);
        // creo una classe che gestisce l'ultima colonna "bottone"
        GestoreBottoneAnnulla gestoreBottone = new GestoreBottoneAnnulla(table1, model);
        colonna.setCellRenderer(gestoreBottone);
        colonna.setCellEditor(gestoreBottone);
    }

    private class GestoreBottoneAnnulla extends AbstractCellEditor implements TableCellRenderer, TableCellEditor {
        private final JButton bottoneRender;
        private final JButton bottoneEditor;
        private Object valoreCella;
        private int rigaCorrente;

        public GestoreBottoneAnnulla(JTable tab, DefaultTableModel modello) {
            this.bottoneRender = new JButton();
            this.bottoneEditor = new JButton();

            this.bottoneEditor.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    fireEditingStopped();
                    bottoneAnnullaActionPerformed(rigaCorrente);
                }
            });
        }

        @Override
        public Component getTableCellRendererComponent(JTable tab, Object val, boolean isSelected, boolean hasFocus, int riga, int col) {
            if (val == null) {
                bottoneRender.setText(""); // Se la cella è vuota non scrive niente sul bottone
            } else {
                bottoneRender.setText(val.toString()); // se c'è scritto annulla lascia annulla
            }
            return bottoneRender;
        }

        @Override
        public Component getTableCellEditorComponent(JTable tab, Object val, boolean isSelected, int riga, int col) {
            this.valoreCella = val;
            this.rigaCorrente = riga;
            if (val == null) {
                bottoneEditor.setText(""); //se la cella è vuota non scrive niente
                bottoneEditor.setEnabled(false); // fa in modo che la cella non sia cliccabile
            } else {
                bottoneEditor.setText(val.toString()); // se c'è scritto annulla lascia annulla
                bottoneEditor.setEnabled(true);

            }
            return bottoneEditor;
        }

        @Override
        public Object getCellEditorValue() {
            return this.valoreCella;
        }
    }

    private void bottoneAnnullaActionPerformed(int rigaSelezionata) {
        AnnullamentoPopup pannelloPopup = getAnnullamentoPopup(rigaSelezionata);

        //Trova la finestra principale
        Window finestraMadre = SwingUtilities.getWindowAncestor(table1);

        // Crea un JDialog
        JDialog dialog = new JDialog(finestraMadre, "Conferma Annullamento", Dialog.ModalityType.APPLICATION_MODAL);

        // Inserisce annullamentoPopup nel JDialog
        dialog.add(pannelloPopup.getPannelloPrincipale());

        //Configurazione grafica del Popup
        dialog.pack(); // Serve per dire a java di prendersi lo spazio necessario
        dialog.setLocationRelativeTo(finestraMadre); //Centra il Popup sulla finestra madre
        // Mostra la finestra
        dialog.setVisible(true);
    }

    private AnnullamentoPopup getAnnullamentoPopup(int rigaSelezionata) {
        DefaultTableModel model = (DefaultTableModel) table1.getModel();

        //passaggio dei dati e formatting della tabella
        long idPrenotazione = (long) model.getValueAt(rigaSelezionata, 0);
        LocalDate data = (LocalDate) model.getValueAt(rigaSelezionata, 1);
        FilaDTO filaDTO = new FilaDTO((int) model.getValueAt(rigaSelezionata, 2));
        int posto = (Integer)  model.getValueAt(rigaSelezionata, 3);
        String servizi = (String) model.getValueAt(rigaSelezionata, 4);
        int costo =  (Integer) model.getValueAt(rigaSelezionata, 5);
        String stato = (String) model.getValueAt(rigaSelezionata, 6);

        dto.PrenotazioneDTO dtoSelezionato = new dto.PrenotazioneDTO(idPrenotazione, data, "", "", filaDTO, posto, servizi, costo, stato);

        return new AnnullamentoPopup(dtoSelezionato, model, rigaSelezionata);
    }

    public JFrame apriConsultaPropriePrenotazioni() {
        JFrame frame = new JFrame("Mie prenotazioni");
        frame.setContentPane(panel);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        return frame;
    }
}



