package boundary;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import controller.ConfiguraStabilimentoController;
import controller.GestionePrenotazioneController;
import dto.OmbrelloneMappaDTO;
import dto.ServizioAggiuntivoDTO;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Date;

public class EffettuaPrenotazioneForm {
    private JPanel mainPanel;
    private JLabel lblOmbrellone;
    private JLabel lblData;
    private JLabel lblDataSelezionata;
    private JLabel lblOmbrelloneSelezionato;
    private JLabel lblServizi;
    private JButton confermaButton;
    private JPanel panelServizi;

    private List<JCheckBox> listaCheckboxServizi = new ArrayList<>();

    public EffettuaPrenotazioneForm(Date dataSeleziona, OmbrelloneMappaDTO ombrelloneScelto) {
        $$$setupUI$$$();
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        lblDataSelezionata.setText(formatter.format(dataSeleziona));
        lblOmbrelloneSelezionato.setText(Integer.toString(ombrelloneScelto.getNumero()));
        JPanel pannelloCheckbox = new JPanel();
        pannelloCheckbox.setLayout(new BoxLayout(pannelloCheckbox, BoxLayout.Y_AXIS));
        for (ServizioAggiuntivoDTO servizio : ConfiguraStabilimentoController.getServizi()) {
            JCheckBox checkBox = new JCheckBox(servizio.getDescrizione());
            checkBox.setActionCommand(String.valueOf(servizio.getIdServizioAggiuntivo()));
            pannelloCheckbox.add(checkBox);
            listaCheckboxServizi.add(checkBox);
        }
        panelServizi.setLayout(new BorderLayout());
        panelServizi.add(pannelloCheckbox, BorderLayout.CENTER);
        panelServizi.revalidate();
        panelServizi.repaint();

        confermaButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                List<Integer> idServiziSelezionati = new ArrayList<>();
                for (JCheckBox checkBox : listaCheckboxServizi) {
                    if (checkBox.isSelected()) {
                        int idServizio = Integer.parseInt(checkBox.getActionCommand());
                        idServiziSelezionati.add(idServizio);
                    }
                }

                boolean successo = GestionePrenotazioneController.effettuaPrenotazione(
                        dataSeleziona,
                        ombrelloneScelto.getNumero(),
                        idServiziSelezionati,
                        1
                );

                if (successo) JOptionPane.showMessageDialog(mainPanel, "Prenotazione effettuata con successo!");
                else JOptionPane.showMessageDialog(mainPanel, "Errore: l'ombrellone potrebbe essere stato appena prenotato da un altro utente.", "Errore", JOptionPane.ERROR_MESSAGE);

                Window window = SwingUtilities.getWindowAncestor(mainPanel);
                if (window != null) {
                    window.dispose();
                }
            }
        });
    }

    public void apriEffettuaPrenotazioneForm() {
        JFrame frame = new JFrame("Riepilogo prenotazione");
        frame.setContentPane(mainPanel);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        frame.setResizable(false);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(7, 2, new Insets(10, 10, 10, 10), -1, -1));
        mainPanel.setMinimumSize(new Dimension(10, 10));
        mainPanel.setPreferredSize(new Dimension(400, 150));
        lblOmbrellone = new JLabel();
        lblOmbrellone.setText("Ombrellone selezionato");
        mainPanel.add(lblOmbrellone, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(278, 17), null, 0, false));
        lblData = new JLabel();
        lblData.setText("Data selezionata");
        mainPanel.add(lblData, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(278, 17), null, 0, false));
        lblServizi = new JLabel();
        lblServizi.setText("Aggiungere eventuali servizi?");
        mainPanel.add(lblServizi, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(278, 17), null, 0, false));
        panelServizi = new JPanel();
        panelServizi.setLayout(new GridLayoutManager(1, 1, new Insets(10, 10, 10, 10), -1, -1));
        mainPanel.add(panelServizi, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        confermaButton = new JButton();
        confermaButton.setText("Conferma");
        mainPanel.add(confermaButton, new GridConstraints(6, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblDataSelezionata = new JLabel();
        lblDataSelezionata.setText("Label");
        mainPanel.add(lblDataSelezionata, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        lblOmbrelloneSelezionato = new JLabel();
        lblOmbrelloneSelezionato.setText("Label");
        mainPanel.add(lblOmbrelloneSelezionato, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        mainPanel.add(spacer1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, new Dimension(278, 11), null, 0, false));
        final Spacer spacer2 = new Spacer();
        mainPanel.add(spacer2, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer3 = new Spacer();
        mainPanel.add(spacer3, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, new Dimension(278, 11), null, 0, false));
        final Spacer spacer4 = new Spacer();
        mainPanel.add(spacer4, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer5 = new Spacer();
        mainPanel.add(spacer5, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, new Dimension(278, 11), null, 0, false));
        final Spacer spacer6 = new Spacer();
        mainPanel.add(spacer6, new GridConstraints(5, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
