package boundary;

import controller.GestionePrenotazioneController;
import dto.PrenotazioneDTO;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import java.awt.*;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import com.toedter.calendar.JDateChooser;

public class ElencoPrenotazioniView extends JFrame {
    private JPanel rootPanel;
    private JButton btnMostraTutte;
    private JScrollPane scrollPanel;
    private JTable tabPrenotazioni;
    private JPanel pnlDateChooser;
    private final DefaultTableModel model;

    public ElencoPrenotazioniView() {
        setTitle("Elenco Prenotazioni");
        setSize(800, 400);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setContentPane(rootPanel);
        JDateChooser dateChooser = new JDateChooser();
        dateChooser.setDateFormatString("dd/MM/yyyy");
        dateChooser.setPreferredSize(new Dimension(120, 25));
        pnlDateChooser.setLayout(new FlowLayout(FlowLayout.LEFT));
        dateChooser.setPreferredSize(
                new Dimension(130, 25)
        );
        pnlDateChooser.add(dateChooser);
        setVisible(true);

        String[] colonne = {
                "ID",
                "Data",
                "Stato",
                "Prezzo"
        };

        model = new DefaultTableModel(colonne, 0);
        tabPrenotazioni.setModel(model);

        dateChooser.setDateFormatString("dd/MM/yyyy");
        dateChooser.setPreferredSize(new Dimension(120, 30));
        dateChooser.getDateEditor()
                .getUiComponent()
                .setFont(new Font("Arial", Font.PLAIN, 14));

        dateChooser.addPropertyChangeListener("date", e -> {
            Date data = dateChooser.getDate();
            LocalDate dataLocale =
                    data.toInstant()
                            .atZone(ZoneId.systemDefault())
                            .toLocalDate();
            aggiornaTabella(GestionePrenotazioneController.consultaPrenotazioniPerDataDTO(dataLocale));
        });

        btnMostraTutte.addActionListener(e -> {
            aggiornaTabella(
                    GestionePrenotazioneController.consultaElencoPrenotazioniDTO()
            );
        });

        btnMostraTutte.addActionListener(e ->
                aggiornaTabella(GestionePrenotazioneController.consultaElencoPrenotazioniDTO())
        );

        aggiornaTabella(GestionePrenotazioneController.consultaElencoPrenotazioniDTO());

        tabPrenotazioni.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                int riga = tabPrenotazioni.getSelectedRow();
                if (riga >= 0) {
                    Long idPrenotazione =
                            ((Number) tabPrenotazioni.getValueAt(riga, 0))
                                    .longValue();
                    PrenotazioneDTO p = GestionePrenotazioneController.consultaPrenotazioneDTO(idPrenotazione);
                    new DettaglioPrenotazioneView(p);
                }
            }
        });
    }


    private void aggiornaTabella(List<PrenotazioneDTO> prenotazioni) {
        model.setRowCount(0);
        System.out.println("Ricevute: " + prenotazioni.size());
        for (PrenotazioneDTO p : prenotazioni) {
            System.out.println(
                    p.getIdPrenotazione() + " "
                            + p.getDataPrenotazione() + " "
                            + p.getStato()
            );
            model.addRow(new Object[]{
                    p.getIdPrenotazione(),
                    p.getDataPrenotazione(),
                    p.getStato(),
                    p.getCosto()
            });
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new GridLayoutManager(4, 3, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("Elenco Prenotazioni");
        rootPanel.add(label1, new GridConstraints(0, 0, 1, 3, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        scrollPanel = new JScrollPane();
        rootPanel.add(scrollPanel, new GridConstraints(2, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        tabPrenotazioni = new JTable();
        scrollPanel.setViewportView(tabPrenotazioni);
        final JLabel label2 = new JLabel();
        label2.setText("Data:");
        rootPanel.add(label2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        btnMostraTutte = new JButton();
        btnMostraTutte.setText("Mostra Tutte");
        rootPanel.add(btnMostraTutte, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        pnlDateChooser = new JPanel();
        pnlDateChooser.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        rootPanel.add(pnlDateChooser, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }

}

