package boundary;

import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class MainFrameGestore {
    private JPanel mainPanel;
    private JLabel homepageLabel;
    private JButton configuraStabilimentoButton;
    private JButton visualizzaOmbrelloniButton;
    private JButton elencoPrenotazioniButton;
    private JButton monitoraggioButton;

    private JFrame frameConfiguraStabilimento;
    private JFrame frameVisualizzaOmbrelloni;
    private JFrame frameElencoPrenotazioni;
    private JFrame frameMonitoraggio;

    public MainFrameGestore() {
        homepageLabel.setText("Homepage Gestore");

        configuraStabilimentoButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (frameConfiguraStabilimento == null || !frameConfiguraStabilimento.isVisible()) {
                    SchermataConfigurazioneStabilimento schermata = new SchermataConfigurazioneStabilimento();
                    frameConfiguraStabilimento = new JFrame("Configura Stabilimento");
                    frameConfiguraStabilimento.setContentPane(schermata.getContentPane());
                    frameConfiguraStabilimento.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    frameConfiguraStabilimento.setResizable(false);
                    frameConfiguraStabilimento.pack();
                    frameConfiguraStabilimento.setLocationRelativeTo(null);
                    frameConfiguraStabilimento.setVisible(true);
                } else {
                    frameConfiguraStabilimento.toFront();
                    frameConfiguraStabilimento.requestFocus();
                }
            }
        });

        visualizzaOmbrelloniButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (frameVisualizzaOmbrelloni == null || !frameVisualizzaOmbrelloni.isVisible()) {
                    MappaOmbrelloniView mappaOmbrelloni = new MappaOmbrelloniView(false);
                    frameVisualizzaOmbrelloni = mappaOmbrelloni.apriMappaOmbrelloniView();
                    frameVisualizzaOmbrelloni.setTitle("Visualizza Ombrelloni");
                    frameVisualizzaOmbrelloni.setLocationRelativeTo(null);
                    frameVisualizzaOmbrelloni.setVisible(true);
                } else {
                    frameVisualizzaOmbrelloni.toFront();
                    frameVisualizzaOmbrelloni.requestFocus();
                }
            }
        });

        elencoPrenotazioniButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JOptionPane.showMessageDialog(null,
                        "Schermata elenco prenotazioni da collegare.");
            }
        });

        monitoraggioButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JOptionPane.showMessageDialog(null,
                        "Schermata monitoraggio da collegare.");
            }
        });
    }

    public JPanel getMainPanel() {
        return mainPanel;
    }

    public static void apriHomepage() {
        JFrame frame = new JFrame("Homepage Gestore");
        MainFrameGestore mainFrame = new MainFrameGestore();
        frame.setContentPane(mainFrame.getMainPanel());
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setResizable(true);
        frame.pack();
        frame.setSize(700, 250);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }
}