package boundary;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class MainFrameCliente {
    private JPanel mainPanel;
    private JLabel homepageLabel;
    private JButton mappaOmbrelloniButton;
    private JButton effettuaPrenotazioneButton;

    private JFrame frameMappaOmbrelloni;
    private JFrame frameEffettuaPrenotazione;

    public MainFrameCliente() {

        homepageLabel.setText("Homepage Cliente");

        mappaOmbrelloniButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (frameMappaOmbrelloni == null || !frameMappaOmbrelloni.isVisible()) {
                    MappaOmbrelloniView mappaOmbrelloni = new MappaOmbrelloniView(false);
                    frameMappaOmbrelloni = mappaOmbrelloni.apriMappaOmbrelloniView();
                    frameMappaOmbrelloni.setLocationRelativeTo(null);
                    frameMappaOmbrelloni.setVisible(true);
                } else {
                    frameMappaOmbrelloni.toFront();
                    frameMappaOmbrelloni.requestFocus();
                }
            }
        });

        effettuaPrenotazioneButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (frameEffettuaPrenotazione == null || !frameEffettuaPrenotazione.isVisible()) {
                    MappaOmbrelloniView effettuaPrenotazione = new MappaOmbrelloniView(true);
                    frameEffettuaPrenotazione = effettuaPrenotazione.apriMappaOmbrelloniView();
                    frameEffettuaPrenotazione.setTitle("Effettua Prenotazione");
                    frameEffettuaPrenotazione.setLocationRelativeTo(null);
                    frameEffettuaPrenotazione.setVisible(true);
                } else {
                    frameEffettuaPrenotazione.toFront();
                    frameEffettuaPrenotazione.requestFocus();
                }
            }
        });
    }

    public static void apriHomepage() {
        JFrame frame = new JFrame("Homepage Cliente");
        MainFrameCliente mainFrame = new MainFrameCliente();
        frame.setContentPane(mainFrame.mainPanel);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); //Variazione
        frame.setResizable(true);
        frame.pack();
        frame.setSize(700, 200);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(3, 2, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.setPreferredSize(new Dimension(400, 100));

        homepageLabel = new JLabel();
        homepageLabel.setAlignmentX(0.5f);
        homepageLabel.setText("Benvenuto");
        mainPanel.add(homepageLabel, new GridConstraints(0, 0, 1, 2,
                GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE,
                GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED,
                null, new Dimension(50, 50), null, 0, false));

        mappaOmbrelloniButton = new JButton();
        mappaOmbrelloniButton.setText("Mappa Ombrelloni");
        mainPanel.add(mappaOmbrelloniButton, new GridConstraints(1, 0, 1, 1,
                GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));

        effettuaPrenotazioneButton = new JButton();
        effettuaPrenotazioneButton.setText("Effettua Prenotazione");
        mainPanel.add(effettuaPrenotazioneButton, new GridConstraints(2, 0, 1, 1,
                GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}