package boundary;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class MainFrameGestore {
    private JPanel mainPanel;
    private JLabel homepageLabel;
    private JButton configuraStabilimentoButton;
    private JButton visualizzaOmbrelloniButton;
    private JButton elencoPrenotazioniButton;
    private JButton monitoraggioButton;

    private JFrame frameConfiguraStabilimento;
    private JFrame frameVisualizzaOmbrelloni;
    private JFrame frameElencoPrenotazioni;
    private JFrame frameMonitoraggio;

    public MainFrameGestore() {
        homepageLabel.setText("Homepage Gestore");

        configuraStabilimentoButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (frameConfiguraStabilimento == null || !frameConfiguraStabilimento.isVisible()) {
                    SchermataConfigurazioneStabilimento schermata = new SchermataConfigurazioneStabilimento();
                    frameConfiguraStabilimento = new JFrame("Configura Stabilimento");
                    frameConfiguraStabilimento.setContentPane(schermata.getContentPane());
                    frameConfiguraStabilimento.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    frameConfiguraStabilimento.setResizable(false);
                    frameConfiguraStabilimento.pack();
                    frameConfiguraStabilimento.setLocationRelativeTo(null);
                    frameConfiguraStabilimento.setVisible(true);
                } else {
                    frameConfiguraStabilimento.toFront();
                    frameConfiguraStabilimento.requestFocus();
                }
            }
        });

        visualizzaOmbrelloniButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (frameVisualizzaOmbrelloni == null || !frameVisualizzaOmbrelloni.isVisible()) {
                    MappaOmbrelloniView mappaOmbrelloni = new MappaOmbrelloniView(false);
                    frameVisualizzaOmbrelloni = mappaOmbrelloni.apriMappaOmbrelloniView();
                    frameVisualizzaOmbrelloni.setTitle("Visualizza Ombrelloni");
                    frameVisualizzaOmbrelloni.setLocationRelativeTo(null);
                    frameVisualizzaOmbrelloni.setVisible(true);
                } else {
                    frameVisualizzaOmbrelloni.toFront();
                    frameVisualizzaOmbrelloni.requestFocus();
                }
            }
        });

        elencoPrenotazioniButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JOptionPane.showMessageDialog(null,
                        "Schermata elenco prenotazioni da collegare.");
            }
        });

        monitoraggioButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                JOptionPane.showMessageDialog(null,
                        "Schermata monitoraggio da collegare.");
            }
        });
    }

    public JPanel getMainPanel() {
        return mainPanel;
    }

    public static void apriHomepage() {
        JFrame frame = new JFrame("Homepage Gestore");
        MainFrameGestore mainFrame = new MainFrameGestore();
        frame.setContentPane(mainFrame.getMainPanel());
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setResizable(true);
        frame.pack();
        frame.setSize(700, 250);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(5, 2, new Insets(0, 0, 0, 0), -1, -1));
        final Spacer spacer1 = new Spacer();
        mainPanel.add(spacer1, new GridConstraints(1, 1, 4, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        homepageLabel = new JLabel();
        homepageLabel.setText("Homepage Gestore");
        mainPanel.add(homepageLabel, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        configuraStabilimentoButton = new JButton();
        configuraStabilimentoButton.setText("Configura Stabilimento");
        mainPanel.add(configuraStabilimentoButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        visualizzaOmbrelloniButton = new JButton();
        visualizzaOmbrelloniButton.setText("Visualizza Ombrelloni");
        mainPanel.add(visualizzaOmbrelloniButton, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        elencoPrenotazioniButton = new JButton();
        elencoPrenotazioniButton.setText("Elenco Prenotazioni");
        mainPanel.add(elencoPrenotazioniButton, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        monitoraggioButton = new JButton();
        monitoraggioButton.setText("Monitoraggio");
        mainPanel.add(monitoraggioButton, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}