package boundary;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class MainFrame {
    private JPanel mainPanel;
    private JLabel homepageLabel;
    private JButton mappaOmbrelloniButton;
    private JButton effettuaPrenotazioneButton;

    private JFrame frameMappaOmbrelloni;
    private JFrame frameEffettuaPrenotazione;

    public MainFrame() {

        mappaOmbrelloniButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (frameMappaOmbrelloni == null || !frameMappaOmbrelloni.isVisible()) {
                    MappaOmbrelloniView mappaOmbrelloni = new MappaOmbrelloniView(false);
                    frameMappaOmbrelloni = mappaOmbrelloni.apriMappaOmbrelloniView();
                    frameMappaOmbrelloni.setLocationRelativeTo(null);
                    frameMappaOmbrelloni.setVisible(true);
                } else {
                    frameMappaOmbrelloni.toFront();
                    frameMappaOmbrelloni.requestFocus();
                }
            }
        });
        effettuaPrenotazioneButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (frameEffettuaPrenotazione == null || !frameEffettuaPrenotazione.isVisible()) {
                    MappaOmbrelloniView effettuaPrenotazione = new MappaOmbrelloniView(true);
                    frameEffettuaPrenotazione = effettuaPrenotazione.apriMappaOmbrelloniView();
                    frameEffettuaPrenotazione.setTitle("Effettua Prenotazione");
                    frameEffettuaPrenotazione.setLocationRelativeTo(null);
                    frameEffettuaPrenotazione.setVisible(true);
                } else {
                    frameEffettuaPrenotazione.toFront();
                    frameEffettuaPrenotazione.requestFocus();
                }
            }
        });
    }

    static void main() {
        JFrame frame = new JFrame("Homepage");
        MainFrame mainFrame = new MainFrame();
        frame.setContentPane(mainFrame.mainPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setResizable(false);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.setPreferredSize(new Dimension(400, 100));
        homepageLabel = new JLabel();
        homepageLabel.setAlignmentX(0.5f);
        homepageLabel.setText("Benvenuto");
        mainPanel.add(homepageLabel, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(50, 50), null, 0, false));
        mappaOmbrelloniButton = new JButton();
        mappaOmbrelloniButton.setText("Mappa Ombrelloni");
        mainPanel.add(mappaOmbrelloniButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        effettuaPrenotazioneButton = new JButton();
        effettuaPrenotazioneButton.setText("EffettuaPrenotazione");
        mainPanel.add(effettuaPrenotazioneButton, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
